<?php if ($layout == 'grid') : ?>
    <span>text<?php echo isset($num) ? ' ' . $num : '';?></span>
<?php else: ?>
	<?php if (isset($longText) && $longText == true) : ?>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non augue tortor. Curabitur venenatis elit eget iaculis sollicitudin. Nulla rutrum ultrices sodales. Fusce lacinia tincidunt dui. Nullam porttitor semper dui sit amet pharetra. Maecenas sapien lacus, rutrum non consectetur sit amet, gravida at quam. Donec quam sapien, volutpat ut luctus sit amet, mollis vel augue. Maecenas efficitur ut diam nec accumsan. Sed libero dui, tempor ac ante sit amet, consectetur porttitor quam. Cras lobortis nisi sed fringilla bibendum. Ut rutrum nibh sit amet est bibendum tempus sit amet in orci. Etiam ut auctor nisl, et sodales tortor. Morbi congue dolor mauris, a accumsan urna cursus eu. Morbi molestie sed urna sit amet maximus. Curabitur vestibulum semper diam eu viverra. Morbi euismod auctor lorem, sit amet varius quam vehicula bibendum.</p>

        <p>Integer nisl mauris, tempus ac egestas sit amet, auctor et arcu. Etiam porttitor odio at diam convallis fringilla. Integer in varius neque. Ut rhoncus gravida tempus. Donec sagittis urna dui, at feugiat lectus eleifend eu. In vel magna fringilla, ultricies lacus non, maximus urna. Curabitur dapibus ac tellus a pellentesque. Sed finibus varius turpis sit amet vestibulum. Pellentesque vitae ante euismod, pellentesque justo nec, ultricies mauris. Ut non consequat metus. Curabitur a sem justo.</p>

        <p>Vestibulum sit amet dignissim tortor. Nullam blandit scelerisque faucibus. Sed viverra felis vel leo vestibulum, sit amet aliquam metus sagittis. Cras commodo ipsum velit, nec aliquet purus rutrum iaculis. Duis congue pellentesque ipsum, nec rhoncus eros rhoncus eu. Ut sit amet lectus ut nibh efficitur sollicitudin. Nam laoreet urna nec diam laoreet, ut vestibulum arcu dignissim. Praesent dictum, mauris sed posuere lobortis, purus turpis euismod sapien, vitae bibendum eros arcu a ante. Mauris convallis enim quis ante iaculis aliquet. Quisque sed blandit diam. Aliquam quis egestas velit. Praesent ullamcorper, neque convallis hendrerit tincidunt, enim nunc pellentesque diam, condimentum congue orci justo nec urna. Vivamus sem neque, porttitor eu elit ornare, sodales ornare turpis. Aliquam dolor velit, tincidunt euismod enim malesuada, gravida egestas purus. Fusce sed tincidunt tortor.</p>

        <p>Phasellus dignissim ullamcorper aliquet. Ut condimentum tincidunt mi vitae tincidunt. Cras varius tincidunt ligula et sodales. Suspendisse elit orci, varius sed elementum sed, tincidunt porttitor lorem. Fusce id leo ut dolor maximus porta ut in justo. Ut nec odio ut orci convallis scelerisque. Ut varius velit neque, non facilisis tortor aliquam at.</p>

        <p>Nullam auctor ultrices libero, at pretium mauris pulvinar et. Suspendisse potenti. Aenean leo neque, lobortis et cursus ac, elementum ut nibh. Cras ut magna nisi. Sed et nisl in metus vulputate iaculis eu eu velit. Morbi ac metus laoreet, imperdiet ipsum eget, ullamcorper elit. Fusce pharetra, elit in sollicitudin venenatis, ex ex porttitor libero, blandit posuere quam ante ut eros. Nam convallis, arcu a blandit scelerisque, quam purus efficitur tortor, nec bibendum ligula risus eget ipsum. Sed ac pulvinar lorem. Ut vulputate justo nulla, id mollis ligula venenatis at. Nullam sodales, ipsum sed viverra facilisis, mauris erat dictum nibh, a posuere tortor eros non elit. Fusce condimentum consectetur lorem in ornare.</p>

        <p>Praesent ornare dui vel sapien cursus, eget vestibulum nibh commodo. Suspendisse dictum dolor non arcu luctus porttitor. Proin aliquet, nunc eget volutpat ultrices, tellus mauris fermentum ex, nec fringilla sem massa vel enim. Etiam ut nisi consectetur lorem pulvinar commodo. Phasellus tortor quam, vestibulum in justo id, imperdiet lacinia nulla. Donec et suscipit metus. Suspendisse potenti. Vestibulum hendrerit dignissim fringilla. Donec consequat malesuada turpis porta imperdiet. Etiam quis ultrices sem, vel tempor ante.</p>

        <p>Cras enim dolor, imperdiet et semper non, rhoncus eget arcu. Aliquam ultricies blandit bibendum. Integer sed bibendum enim. Praesent eu urna eget mi malesuada blandit sit amet nec quam. Morbi eu elit felis. Pellentesque pretium nulla ac diam faucibus, sit amet sollicitudin nulla imperdiet. Curabitur quis eros gravida, varius ante sed, finibus ante. Fusce facilisis odio vel neque facilisis pretium. Curabitur orci diam, posuere ac suscipit id, varius et orci. Donec accumsan semper ante, et rhoncus velit efficitur id. Aenean ut erat ac nulla viverra mollis vel in elit.</p>

        <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent in nibh sem. Fusce finibus consequat posuere. Nunc egestas dui non imperdiet varius. Praesent sagittis, sapien sit amet accumsan cursus, lectus quam pretium mauris, et eleifend justo dolor vitae nunc. Aenean in purus dui. Praesent imperdiet non leo sed viverra.</p>

        <p>Praesent mauris erat, scelerisque ac congue maximus, ornare eget urna. Sed a feugiat nibh. Duis pharetra, turpis nec tristique euismod, nisi tellus tincidunt metus, vitae iaculis nibh nulla in felis. Nunc in ipsum a eros placerat faucibus. Donec fermentum, leo quis commodo congue, nibh orci volutpat dui, ac hendrerit justo massa vitae nulla. Sed dignissim imperdiet facilisis. Vivamus eu leo quis leo pellentesque maximus. Duis lobortis lectus elit, sed molestie velit pretium id. Etiam volutpat ex sit amet ultricies facilisis. Donec eleifend orci id aliquam lobortis. Ut rutrum ac nisi vehicula volutpat.</p>

        <p>Maecenas dignissim massa massa, ac imperdiet lacus sodales ut. Vestibulum ultricies aliquam erat, id iaculis enim semper quis. Curabitur lectus ligula, hendrerit et ante sed, tristique imperdiet lacus. Suspendisse sit amet justo non diam fringilla consectetur. Vivamus lobortis felis odio, molestie placerat est tincidunt ut. Cras placerat tortor non dolor posuere, non porttitor ante fringilla. Suspendisse efficitur auctor magna vel placerat. Integer id eros a sem aliquet egestas. Fusce quis nulla est. Aliquam et odio vitae metus fringilla dictum sit amet eget risus. Mauris viverra velit a ligula auctor, in hendrerit nisl bibendum.</p>

        <p>In quis metus posuere, semper quam id, pharetra tortor. Praesent in ante nec purus pretium dignissim. Nam eget diam ac mi egestas gravida. Vestibulum faucibus pretium tellus eget auctor. In condimentum risus vel leo pretium, quis feugiat lorem dignissim. Vestibulum varius, mauris ac dapibus ultricies, sapien nulla feugiat dui, in bibendum nisi nibh non arcu. Aliquam leo felis, consectetur ut nibh sed, dapibus consectetur risus. Fusce id orci quis ex dignissim consequat non eget sem.</p>

        <p>Maecenas varius diam dictum est interdum, sit amet maximus tortor aliquet. Nunc mattis, ante quis accumsan gravida, libero risus maximus magna, at tempor mi nibh non neque. Integer feugiat ipsum sem, in rhoncus velit rhoncus sit amet. Nam tincidunt diam et quam placerat, sed egestas sem tincidunt. Cras euismod bibendum lorem at placerat. Ut scelerisque ligula ante, in imperdiet libero blandit vitae. Praesent sit amet elit urna. Sed vehicula ut tortor ac interdum. Morbi scelerisque risus eget urna suscipit, ac ullamcorper ligula bibendum.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque malesuada cursus. Suspendisse volutpat dolor eu justo lobortis, eu tincidunt justo molestie. Ut non elit accumsan, elementum justo vel, scelerisque odio. In eleifend turpis eu turpis malesuada blandit. Ut porttitor interdum iaculis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris et lectus ac nisi porttitor commodo.</p>

        <p>Nunc eget ultricies nisl, id ultrices augue. Vestibulum sit amet libero tincidunt, vulputate purus nec, volutpat purus. Morbi urna ante, rutrum at ligula id, commodo aliquet magna. Suspendisse sagittis, dolor a tincidunt maximus, tellus eros accumsan quam, at semper eros lectus vitae sem. Proin malesuada risus non elit faucibus, vel molestie odio hendrerit. Mauris justo dolor, aliquam id condimentum non, scelerisque non dui. Mauris orci metus, rutrum posuere semper et, convallis non augue. Nam accumsan purus dolor, quis volutpat orci convallis sed.</p>

        <p>Curabitur hendrerit libero lectus, at consequat lacus mollis sed. Sed vitae egestas odio. Integer vulputate tortor vel nulla tristique, et accumsan elit luctus. Vivamus suscipit vitae nunc non lacinia. Proin ipsum ipsum, lobortis ultrices venenatis in, vestibulum eu massa. Suspendisse molestie tempus dapibus. Pellentesque varius nulla congue metus laoreet, nec posuere turpis semper. Sed ornare erat risus, nec tincidunt sapien commodo at. Curabitur sagittis ultrices tellus a feugiat. In consequat finibus lectus, vulputate consequat urna rhoncus et. Praesent vitae sapien pellentesque nunc congue euismod ut volutpat nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec posuere sapien eu diam vulputate, ut venenatis augue dictum. Suspendisse velit nulla, vehicula et nulla fermentum, suscipit dictum nisl. Sed a sapien vel erat imperdiet malesuada vitae eget sapien.</p>
	<?php else: ?>
        <span>text</span>
	<?php endif; ?>
<?php endif; ?>